services:
  app:
    build: .
    container_name: lms-app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - mongodb
      - rabbitmq

  redis:
    image: redis:7-alpine
    container_name: lms-redis
    ports:
      - "6379:6379"

  mongodb:
    image: mongo
    container_name: lms-mongodb
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: lms-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  celery-worker:
    build: .
    container_name: lms-celery-worker
    command: celery -A config worker -l info
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
      - redis
      - app

  celery-beat:
    build: .
    container_name: lms-celery-beat
    command: celery -A config beat -l info
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
      - redis
      - app

  flower:
    image: mher/flower
    container_name: lms-flower
    command: celery --broker=amqp://guest:guest@rabbitmq:5672// flower
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq
