services:
  app:
    build: .
    container_name: lms-app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - mongodb

  redis:
    image: redis:7-alpine
    container_name: lms-redis
    ports:
      - "6379:6379"

  mongodb:
    image: mongo
    container_name: lms-mongodb
    ports:
      - "27017:27017"
